resources:
- name: eyalbe4_mvn_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: eyalbe4/mvn-example-pipelines
    gitProvider: github_eyalbe4_mvn_example_pipelines_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
pipelines:
- name: eyalbe4_mvn_example_pipelines_pipeline
  configuration:
    runtime:
      type: image
      image:
        custom:
          name: releases-docker.jfrog.io/jfrog/jfrog-cli-full
          tag: latest
  steps:
  - name: Build
    type: Bash
    configuration:
      inputResources:
      - name: eyalbe4_mvn_example_pipelines_gitResource
      integrations:
      - name: rt_eyalbe4_mvn_example_pipelines_integration
    execution:
      onExecute:
      - cd $res_eyalbe4_mvn_example_pipelines_gitResource_resourcePath
      - export CI=true
      - export JFROG_CLI_BUILD_NAME=mvn-example-pipelines-main
      - export JFROG_CLI_BUILD_NUMBER=$run_number
      - export JFROG_CLI_BUILD_URL=$step_url
      - export JFROG_BUILD_RESULTS=PASS
      - jfrog c add eyalbe4_mvn_example_pipelines_serverId --artifactory-url $int_rt_eyalbe4_mvn_example_pipelines_integration_url
        --user $int_rt_eyalbe4_mvn_example_pipelines_integration_user --apikey $int_rt_eyalbe4_mvn_example_pipelines_integration_apikey
        --enc-password=false
      - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname
        | xargs dirname`
      - jfrog rt mvn-config --server-id-resolve eyalbe4_mvn_example_pipelines_serverId
        --repo-resolve-releases maven-central --repo-resolve-snapshots maven-central
      - jfrog rt mvn clean install
      - jfrog rt bag
      - jfrog rt bce
      - jfrog rt bp
      onComplete:
      - update_commit_status eyalbe4_mvn_example_pipelines_gitResource
      onFailure:
      - export JFROG_BUILD_RESULTS=FAIL
      - jfrog rt bce
      - jfrog rt bp
